Added missing payload to agent_config edit api
tenable/pyTenable pull request #287
Opened 2021-03-25 10:03 UTC by tushar-balwani

# Description

**Issue:** Updated payload was not provided to agent_exclusion edit API.
**Changes done:**  Added updated payload to agent_exclusion edit API and updated software_update condition check

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] **Added test:** `test_agentconfig_edit_disable_softwareupdate` : added to check change of  software_update key
- [x] **Updated existing tests:** 
`test_agentconfig_edit_set_autounlink` and `test_agentconfig_edit_disable_autounlink` : added assert to check changes are working or not.

**Test Configuration**:
* Python Version(s) Tested: 3.8.6
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-05-11 22:18 UTC, levwais reviewed
lgtm

2021-05-26 10:24 UTC, valliammal requested changes
Always wildcard import is not permittted , this is in test_agent_config.py

2021-05-26 10:25 UTC, valliammal approved these changes
Changes are approved, Looking nice

2021-06-03 17:59 UTC, levwais approved these changes

2021-06-03 17:59 UTC, merged