IN-419 issues
tenable/pyTenable pull request #368
Opened 2021-07-13 12:04 UTC by dheerajrp

# Description

Addressed the issues in the jira IN-419

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Pytest

**Test Configuration**:
* Python Version(s) Tested: Python 3.6, 3.7, 3.8, 3.9
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-13 13:30 UTC, mvalliammal reviewed
Line 113, the return statement is there, so normal return will not be done, except with specific condition. So other than the conditional return, if that is not coming, then normal return needs to be present

2021-07-13 13:37 UTC, mvalliammal reviewed
Wrong import order in line 10 in tests/io/test_credentials.py
In test_plugins.py, 
line 46 is error with variables, it is represented as 'a' 
Unused import checker and wrong order import also present.

2021-07-14 11:59 UTC, tushar-balwani requested changes

2021-07-14 11:59 UTC, tushar-balwani commented on tests/io/test_agent_groups.py
> +        api.agent_groups.add_agent(agentgroup['id'], each_agent['id'])
why we are adding individual agent to group instead of passing all at once

2021-07-14 11:59 UTC, tushar-balwani commented on tests/io/test_agent_groups.py
> +        api.agent_groups.delete_agent(agentgroup['id'], each_agent['id'])
why adding and deleting agents in loop

2021-07-14 11:59 UTC, tushar-balwani commented on tests/io/test_agent_groups.py
> +        api.agent_groups.add_agent(agentgroup['id'], *alist)
why creating multi-value list of same agent

2021-07-14 11:59 UTC, tushar-balwani commented on tests/io/test_agent_groups.py
> +                                        )
why same id is passed twice

2021-07-14 11:59 UTC, tushar-balwani commented on tests/io/test_agent_groups.py
> +                                          )
why adding same agent id twice

2021-07-29 10:46 UTC, mvalliammal approved these changes
I approved the changes

2021-08-31 18:56 UTC, closed without merging