Added PYPI
tenable/pyTenable pull request #390
Opened 2021-07-26 08:23 UTC by mvalliammal

# Description

Done all the needed for the addition of PYPI

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2021-07-26 08:27 UTC, rboergertenable commented on Jenkinsfile
> +    if (env.BRANCH_NAME == 'master' && releaseBuild == 'Yes') {
This variable is no longer defined. Please make this a build parameter.

2021-07-26 08:31 UTC, rboergertenable commented on Jenkinsfile
> +    if (env.BRANCH_NAME == 'master' && releaseBuild == 'Yes') {
Example here: 

https://github.eng.tenable.com/Product/kafka-connect-configurator/blob/32cf403cc6153cfcbe3e7e8c25c9c5b776d0a6cc/Jenkinsfile#L10

2021-07-26 08:47 UTC, rboergertenable commented on Jenkinsfile
> +
Please remove the unneeded blank lines in the Jenkinsfile.

2021-07-26 08:50 UTC, rboergertenable commented on Jenkinsfile
> +
This parameter should only be added on master.

i.e.

if (script.env.BRANCH_NAME == 'master') {
....

2021-07-26 08:52 UTC, rboergertenable commented on Jenkinsfile
> +PropertiesHelper.defaultCICDProperties(this, 0, this.&addParameters)
We should disable the params that we don't need:

i.e. 

replace this, 0 

with

this, Constants.PROP_NOCONSEC | Constants.PROP_NOSCHEDULE

2021-07-26 09:15 UTC, rboergertenable commented on Jenkinsfile
> +if (env.BRANCH_NAME == 'master') {
Please move inside the function. witt script.env.

2021-07-26 09:49 UTC, rboergertenable commented on Jenkinsfile
> +        theParams
Please move below the closing bracket of the if

2021-07-26 11:06 UTC, rboergertenable requested changes

2021-07-26 11:06 UTC, rboergertenable commented on Jenkinsfile
> +if (env.BRANCH_NAME == 'MASTER') {
Please remove this. The build parameters are there to allow QG overwrites. They are valid on feature branches as well.

2021-09-22 22:59 UTC, closed without merging

2021-09-22 22:59 UTC, SteveMcGrath reviewed
Rejecting as Jenkinsfile will not be used