Added support for TenableAD license APIs
tenable/pyTenable pull request #510
Opened 2022-01-03 12:26 UTC by tushar-balwani

# Description

Added `Tenable.AD License APIs`

- Get license singleton. (_details_)
- Create new license singleton (_create_)

_updated docs to support license api details_

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added tests for license endpoints to test responses
- [x] Added schema tests for testing payload inputs and response dict validation

**Test Configuration**:
* Python Version(s) Tested: 3.8.6
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-19 15:58 UTC, SteveMcGrath requested changes

2022-01-19 15:58 UTC, SteveMcGrath commented on tenable/ad/ldap_configuration/schema.py
> +        return convert_keys_to_camel(data, special=[SEARCH_USER_DN])
no longer necessary per #526

2022-01-19 15:58 UTC, SteveMcGrath commented on tenable/ad/constants.py
> +EXPIRATION_DATE_UTC: str = 'expiration_date_utc'  # ad-license
no longer necessary per #526

2022-01-20 09:30 UTC, tushar-balwani commented on tenable/ad/license/api.py
> +        }))
implemented suggested changes

2022-01-20 09:30 UTC, tushar-balwani commented on tests/ad/license/test_license_api.py
> +    resp = api.license.create(ad_license='license')
implemented suggested changes

2022-01-20 09:31 UTC, tushar-balwani commented on tenable/ad/ldap_configuration/schema.py
> +        return convert_keys_to_camel(data, special=[SEARCH_USER_DN])
removed pre_load method

2022-01-20 09:31 UTC, tushar-balwani commented on tenable/ad/constants.py
> +EXPIRATION_DATE_UTC: str = 'expiration_date_utc'  # ad-license
removed constants file

2024-05-21 19:13 UTC, SteveMcGrath approved these changes

2024-05-21 19:17 UTC, merged