Added support for TenableAD attack type option APIs
tenable/pyTenable pull request #516
Opened 2022-01-12 11:22 UTC by tushar-balwani

# Description

Added `Tenable.AD Attack Type Option` APIs

- Get all the attack type options related to a profile and attack type. (_get_)
- Create attack type options related to a profile and attack type. (_create_)

_updated docs to support attack type option api details_

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added tests for attack type option endpoints to test responses
- [x] Added schema tests for testing payload inputs and response dict validation

**Test Configuration**:
* Python Version(s) Tested: 3.8.6
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-19 15:47 UTC, SteveMcGrath requested changes

2022-01-19 15:47 UTC, SteveMcGrath commented on tenable/ad/attack_type_options/schema.py
> +        return convert_keys_to_camel(data)
#526 Negates this

2022-01-20 09:33 UTC, tushar-balwani commented on tenable/ad/attack_type_options/schema.py
> +        return convert_keys_to_camel(data)
removed pre_load method

2024-05-21 19:37 UTC, SteveMcGrath approved these changes

2024-05-21 19:42 UTC, merged