Added support for TenableAD AD Object APIs
tenable/pyTenable pull request #525
Opened 2022-01-19 13:29 UTC by tushar-balwani

# Description

Added `Tenable.AD AD Object APIs`

- Get ad-object instance by id. (_details_)
- Retrieve an AD object by id that have deviances for a specific profile and checker (_details_by_profile_and_checker_)
- Get ad-object instance by id. (_details_by_event_)
- Get one ad-object changes between a given event and the event which precedes it (_get_changes_)
- Search all AD objects having deviances by profile by checker (_search_all_)

_updated docs to support ad object api details_

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added tests for ad object endpoints to test responses
- [x] Added schema tests for testing payload inputs and response dict validation

**Test Configuration**:
* Python Version(s) Tested: 3.8.6
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-19 15:46 UTC, SteveMcGrath requested changes

2022-01-19 15:46 UTC, SteveMcGrath commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
#526 negates this

2022-01-19 15:46 UTC, SteveMcGrath commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
#526 negates this

2022-01-19 15:46 UTC, SteveMcGrath commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
#526 negates this

2022-01-20 09:35 UTC, tushar-balwani commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
removed pre_load method

2022-01-20 09:35 UTC, tushar-balwani commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
removed pre_load method

2022-01-20 09:35 UTC, tushar-balwani commented on tenable/ad/ad_object/schema.py
> +        return convert_keys_to_camel(data)
removed pre_load method

2024-05-21 19:44 UTC, SteveMcGrath approved these changes

2024-05-21 19:49 UTC, merged