Create reports_definition.py
tenable/pyTenable pull request #656
Opened 2022-12-07 13:55 UTC by samwmarsh

Tenable SC launch reports using ID in pytenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-09 05:41 UTC, aseemsavio reviewed
Could you provide information on how this was tested? You can refer to existing tests in this directory `tests/sc/`.

2023-01-09 13:37 UTC, aseemsavio commented
Hey @samwmarsh no problem at all! We include tests that confirms the behaviour of a new feature we're adding with the respective pull request. Give me some time, I'll let you know the changes required.

2023-01-09 19:48 UTC, SteveMcGrath requested changes

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/__init__.py
> +    def reports_definition(self):
Should be using a more correct name that conforms to the rest of the package

```suggestion
    def report_definitions(self):
```

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/reports_definition.py
> +class ReportsDefinitionAPI(SCEndpoint):
Should be using a more correct name that conforms to the rest of the package

```suggestion
class ReportDefinitionsAPI(SCEndpoint):
```

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/__init__.py
> +from .reports_definition import ReportsDefinitionAPI
Should be using a more correct name that conforms to the rest of the package

```suggestion
from .report_definitions import ReportDefinitionsAPI
```

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/reports_definition.py
> +        :sc-api:`reports-definition: launch <ReportsDefinition.html#ReportsDefinitionRESTReference-/reportDefinition/{id}/launch>`
```suggestion
        :sc-api:`report-definitions: launch <ReportsDefinition.html#ReportsDefinitionRESTReference-/reportDefinition/{id}/launch>`
```

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/reports_definition.py
> +            >>> running = sc.reports_definition.launch(1)
```suggestion
            >>> running = sc.report_definitions.launch(1)
```

2023-01-09 19:48 UTC, SteveMcGrath commented on tenable/sc/__init__.py
> +        return ReportsDefinitionAPI(self)
```suggestion
        return ReportDefinitionsAPI(self)
```

2023-01-10 07:17 UTC, samwmarsh commented
@aseemsavio all changes merged thanks

2023-01-25 11:47 UTC, samwmarsh commented
@SteveMcGrath that's all sorted, anything blocking this merge now?

2023-01-25 17:57 UTC, SteveMcGrath commented
I'd say there are still some issues just looking at the test suite.

https://github.com/tenable/pyTenable/actions/runs/3881092089/jobs/6619727711#step:5:258

2024-05-22 08:49 UTC, samwmarsh commented
@SteveMcGrath sorry for the delay on this one, I think I've resolved the test suite issues - seemed to be an issue with typo between file name and imports.

2024-11-08 10:06 UTC, samwmarsh commented
@SteveMcGrath anything this is waiting on?

2024-11-21 18:20 UTC, SteveMcGrath reviewed
Aside from missing unit tests, looks good.

2024-11-21 18:22 UTC, SteveMcGrath commented
Apologize for the delay, this one got pushed to the bottom of the stack.  if you're willing to write the unit tests, I have no issues getting this approved.

2024-11-21 20:57 UTC, samwmarsh commented
Not a python dev by any means but hows that? all checks seem happy.

2024-11-21 21:34 UTC, SteveMcGrath commented
The two tests you wrote look great, just need a test with a success as well.  Not anything crazy, we just need to assert that were getting a valid response.  maybe check that the ID exists in the response and it should be ready to merge.

2024-11-21 21:40 UTC, samwmarsh commented
Something like that?

2024-11-21 21:40 UTC, SteveMcGrath approved these changes

2024-11-21 21:48 UTC, samwmarsh commented
```FAILED tests/sc/test_report_definition.py::test_report_definition_launch_success - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='securitycenter.home.cugnet.net', port=443): Max retries exceeded with url: /rest/reportDefinition/1/launch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63a12b2990>: Failed to establish a new connection: [Errno -2] Name or service not known'))```

I copied this from a different test, is this ok or is there a host value this should be to pass?

2024-11-21 21:50 UTC, SteveMcGrath commented on tests/sc/test_report_definition.py
> +def test_report_definition_launch_success(security_center):
Solves https://github.com/tenable/pyTenable/actions/runs/11962140227/job/33349851654?pr=656#step:7:808

```suggestion

@pytest.mark.vcr()
def test_report_definition_launch_success(security_center):
```

2024-11-21 22:41 UTC, SteveMcGrath commented on tests/sc/cassettes/test_report_definition_launch_success.yaml
> +version: 1
```suggestion
interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Cookie: [TNS_SESSIONID=SESSIONID]
      User-Agent: [pyTenable/1.5.3 (pyTenable/1.5.3; Python/3.9.13)]
      X-SecurityCenter: ['0000000000']
    method: POST
    uri: https://securitycenter.home.cugnet.net/rest/reportDefinition/1/launch
  response:
    body: {string: !!python/unicode '{"type" : "regular","response" : {"reportDefinitionID" : "1","reportResult" : {"creatorID" : "2","ownerID" : "2","ownerGID" : "1","reportDefinitionID" : "7","jobID" : "113868","name" : "CS-4700 Iterator","description" : "","type" : "pdf","status" : "Queued","errorDetails" : "","totalSteps" : -1,"completedSteps" : 0,"startTime" : -1,"finishTime" : 0,"pubSites" : [],"id" : "1"}}, "error_code" : 0, "error_msg" : "", "warnings" : [], "timestamp" : 1434567869}'}
    headers:
      cache-control: ['no-store, no-cache, must-revalidate']
      connection: [Keep-Alive]
      content-length: ['983']
      content-type: [application/json]
      date: ['Mon, 08 Apr 2019 13:56:30 GMT']
      expires: ['Thu, 19 Nov 1981 08:52:00 GMT']
      keep-alive: ['timeout=15, max=100']
      pragma: [no-cache]
      securitycenter: [5.8.0]
      server: [Apache]
      strict-transport-security: [max-age=31536000; includeSubDomains]
      x-content-type-options: [nosniff]
      x-frame-options: [DENY]
      x-xss-protection: [1; mode=block]
    status: {code: 200, message: OK}
version: 1
```

2024-11-21 22:41 UTC, SteveMcGrath commented on tests/sc/test_report_definition.py
> +    check(report['reportResult'], 'id', int)
```suggestion
    check(report['reportResult'], 'id', str)
```

2024-11-21 22:43 UTC, samwmarsh commented
Thanks @SteveMcGrath, apologies I've not got access to .sc from my public github location so it was guesswork based off of the api docs!

2024-11-21 22:44 UTC, SteveMcGrath commented
Not a problem, it appeared that the JSON you posted in the cassette wasn't valid, so i tweaked it.

2024-11-21 22:47 UTC, merged