Was integration
tenable/pyTenable pull request #690
Opened 2023-03-29 09:06 UTC by aseemsavio

# Description

Added support for WAS export

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Tests with Cassettes
- [x] manual tests using scripts - example script is as follows.

```
import logging

from tenable.io import TenableIO

if __name__ == '__main__':
    tio = TenableIO(access_key="ACCESS_KEY", secret_key="SECRET_KEY")

    logging.basicConfig(level=logging.DEBUG)

    findings = tio.was.export(
        and_filter=[
            ("scans_started_at", "gte", "2023/03/20"),
            ("scans_status", "contains", ["completed"])
        ]
    )

    for f in findings:
        print(f["plugin_id"])
```

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-30 10:38 UTC, dandamudi1414 requested changes

2023-03-30 10:38 UTC, dandamudi1414 commented on tenable/io/was/iterator.py
> +        self.page = self._api.download_scan_report(current_target_scan_id)["findings"]
As per the mapping document we need the finalized_at timestamp for checkpoint logic and scan_id and config_id as well for dashboards

2023-04-04 05:52 UTC, dandamudi1414 commented on tenable/io/was/api.py
> +    def download_scan_report(self, scan_uuid: str) -> Dict:
we need to support other formats as well CSV, PDF, XML, ...

2023-04-27 06:23 UTC, dandamudi1414 approved these changes
looks good to me

2023-04-27 13:15 UTC, varap11 approved these changes

2023-04-27 14:01 UTC, merged