Updated Security Center API documentation links and Developer Portal links.
tenable/pyTenable pull request #705
Opened 2023-06-05 01:51 UTC by lanz

# Description

Updated the Security Center API documentation links and the Tenable Developer Portal links.

These updates were needed due changes to the URL structure for the Security Center documentation on docs.tenable.com for product rebranding and other updates. Additionally, the links to the Developer Portal were using outdated paths.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I verified the links would work based on my access to the docs.tenable.com and developer.tenable.com source directory structures. I also manually tested the links.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-05 15:54 UTC, aseemsavio requested changes
Hi, Thanks for submitting the pull request. Appreciate you spending the time and effort. I've requested some changes. Please feel free to reach me if you have any questions.

Also, please make sure to use the latest branch of master as there are some errors seen in the test cases.

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/policies.py
> +        :sc-api:`scan-policy: edit <Scan-Policy.htm#policy_id_PATCH>`
fragment identifier should be "policy_uuid_PATCH"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/policies.py
> +        :sc-api:`scan-policy: delete <Scan-Policy.htm#policy_id_DELETE>`
fragment identifier should be "policy_uuid_DELETE"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        :sc-api:`repository: delete <Repository.htm#repository_id_DELETE>`
fragment identifier should be "repository_uuid_DELETE"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        :sc-api:`repository: edit <Repository.htm#repository_id_PATCH>`
fragment identifier should be "repository_uuid_PATCH"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/recastRiskRule>`
fragment id should be "repository_uuid_recastRiskRule_GET"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/assetIntersections>`
fragment id should be "repository_uuid_assetIntersections_GET"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        :sc-api:`repository: import <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/import>`
fragment ID should be "repository_uuid_import_POST"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        :sc-api:`repository: export <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/export>`
fragment ID should be "repository_uuid_export_GET"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        :sc-api:`repository: sync <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/sync>`
fragment id should be "repository_uuid_sync_POST"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/updateMobileData>`
fragment ID should be "repository_uuid_updateMobileData_POST"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        <Repository.htm#RepositoryRESTReference-/repository/{repository_id}/deviceInfo>`
fragment ID should be "repository_uuid_deviceInfo_GET"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/repositories.py
> +        `repository: ip info <Repository.htm#RepositoryRESTReference-/repository/{id}/ipInfo>`
Add ":sc-api:" in the starting of the string.

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scan_instances.py
> +        "sc-api:`scan-result: pause <Scan-Result.htm#ScanResultRESTReference-/scanResult/{id}/pause>`
Remove the " symbol at the start of the line.

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scan_zones.py
> +        :sc-api:`scan-zone: edit <Scan-Zone.htm#zone_id_PATCH>`
fragment ID should be "zone_uuid_PATCH"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scan_zones.py
> +        :sc-api:`scan-zone: delete <Scan-Zone.htm#zone_id_DELETE>`
fragment ID should be "zone_uuid_DELETE"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scanners.py
> +        :sc-api:`scanner: details <Scanner.htm#scanner_POST>`
fragment id should be "ScannerRESTReference-/scanner"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scans.py
> +        :sc-api:scan: list <Scan.htm#scan_GET>`
```
Add the ` symbol before "scan:"
```

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/scans.py
> +        :sc-api:`scan: details <Scan.htm#ScanRESTReference-/scan/{id}>`
The SC documentation does not have a way to copy the CSS fragment Identifier for some of the API endpoints.. Probably need to to reach docs team to fix it. Here's the link in question: https://docs.tenable.com/security-center/api/Scan.htm#ScanRESTReference-/scan/{id}/launch

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/system.py
> +        :sc-api:'system: get <System.htm#system_GET>`
```
:sc-api:'system:

Here, the ' sign after "api" should be `
```

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/users.py
> +        :sc-api:`user: edit <User.htm#user_id_PATCH>`
fragment ID should be "user_uuid_PATCH"

2023-06-05 15:54 UTC, aseemsavio commented on tenable/sc/users.py
> +        :sc-api:`user: delete <User.htm#user_id_DELETE>`
fragment ID should be "user_uuid_DELETE"

2023-06-08 03:06 UTC, lanz commented
> Hi, Thanks for submitting the pull request. Appreciate you spending the time and effort. I've requested some changes. Please feel free to reach me if you have any questions.
> 
> Also, please make sure to use the latest branch of master as there are some errors seen in the test cases.

Thank you for the very quick review @aseemsavio, I've made the requested changes.

2023-06-12 07:39 UTC, aseemsavio commented
LGTM

2023-06-12 07:41 UTC, aseemsavio approved these changes

2023-06-12 09:05 UTC, varap11 approved these changes

2023-06-12 09:06 UTC, merged