Adding support for GET /api/v1/vectors endpoint
tenable/pyTenable pull request #818
Opened 2024-07-17 08:26 UTC by naumraviz

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-17 15:32 UTC, SteveMcGrath requested changes

2024-07-17 15:33 UTC, SteveMcGrath commented
For some reason the tests arent validating out the new code either...

```
tenable/apa/vectors/api.py                            22      9    59%   35-42, 129-139
```

https://github.com/tenable/pyTenable/actions/runs/9970892846/job/27550762173#step:5:1102

2024-07-18 04:33 UTC, naumraviz commented on tenable/apa/vectors/api.py
> +        print(self._next_token)
Hey 
In this endpoint we only support offset based pagination for now-  I fixed the method

2024-07-18 04:34 UTC, naumraviz commented on tenable/apa/vectors/api.py
> +                      "value":"2024-05-30T12:28:11.528118"}``
Please review this again

2024-07-18 04:54 UTC, naumraviz commented on tenable/apa/vectors/api.py
> +             ...     filter='value',
Done

2024-07-23 07:55 UTC, naumraviz commented
@SteveMcGrath Coverage looks fine now 
https://github.com/tenable/pyTenable/actions/runs/10036435064/job/27734176187?pr=818

2024-07-23 16:11 UTC, SteveMcGrath approved these changes

2024-07-23 16:11 UTC, merged